import AdminMapEditor from "@/components/AdminMapEditor";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "News",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <AdminMapEditor />
    </div>
  );
};

export default page;
