import { ColumnDef } from "@tanstack/react-table";
import { Marker } from "@/typescript/interfaces/markers";
import DataTable from "@/components/DataTable";
import axios from "axios";
import { Metadata } from "next";

const markerColumns: ColumnDef<Marker>[] = [
  { header: "ID", accessorKey: "id" },
  { header: "Name", accessorKey: "name" },
  { header: "Latitude", accessorKey: "lat" },
  { header: "Longitude", accessorKey: "lng" },
  { header: "Description", accessorKey: "description" },
  { header: "Date", accessorKey: "date" },
];

export const metadata: Metadata = {
  title: "Markers",
  description: "Generated by create next app",
};

const MarkersPage = async () => {
  const res = await axios.get("http://localhost:3000/api/map-data/marker");
  const markers: Marker[] = res.data;

  return (
    <div className="max-w-5xl mx-auto p-6">
      <DataTable
        data={markers}
        columns={markerColumns}
        enableSearch
        enableDateFilter
        searchField="name"
        dateField="date"
        tableHead="Markers list"
      />
    </div>
  );
};

export default MarkersPage;
