import { ColumnDef } from "@tanstack/react-table";
import DataTable from "@/components/DataTable";
import { Polygon } from "@/typescript/interfaces/polygon";
import axios from "axios";
import { Metadata } from "next";

const polygonColumns: ColumnDef<Polygon>[] = [
  { header: "ID", accessorKey: "id" },
  { header: "Name", accessorKey: "name" },
  { header: "Description", accessorKey: "description" },
  { header: "Date", accessorKey: "date" },
  {
    header: "Points",
    accessorKey: "points",
  },
];
export const metadata: Metadata = {
  title: "Polygon",
  description: "Generated by create next app",
};

const PolygonPage = async () => {
  const res = await axios.get("http://localhost:3000/api/map-data/polygon");
  const polygons: Polygon[] = res.data;
  return (
    <div className="max-w-5xl mx-auto p-6">
      <DataTable
        data={polygons}
        columns={polygonColumns}
        enableSearch
        enableDateFilter
        searchField="name"
        dateField="date"
        tableHead="Polygon list"
      />
    </div>
  );
};

export default PolygonPage;
